# Generated by Django 6.0.2 on 2026-02-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['series', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season')),
            ],
            options={
                'ordering': ['season', 'number'],
                'unique_together': {('season', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='series.episode')),
            ],
            options={
                'ordering': ['episode', 'number'],
                'unique_together': {('episode', 'number')},
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('series', models.ManyToManyField(blank=True, related_name='characters', to='series.series')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('script', models.TextField(blank=True, help_text='Script/dialogue for this shot')),
                ('background', models.CharField(blank=True, help_text='Background description', max_length=500)),
                ('camera_angle', models.CharField(blank=True, help_text='Camera angle description', max_length=500)),
                ('camera_movement', models.CharField(blank=True, help_text='Camera movement description', max_length=500)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='series.sequence')),
            ],
            options={
                'ordering': ['sequence', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ShotCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.character')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.shot')),
            ],
        ),
        migrations.AddField(
            model_name='shot',
            name='characters',
            field=models.ManyToManyField(related_name='shots', through='series.ShotCharacter', to='series.character'),
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to='series.character')),
            ],
            options={
                'ordering': ['character', 'name'],
            },
        ),
        migrations.AddField(
            model_name='shotcharacter',
            name='wardrobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.wardrobeitem'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('sequence', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='shotcharacter',
            unique_together={('shot', 'character')},
        ),
    ]
