# Generated by Django 6.0.2 on 2026-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='script',
            field=models.TextField(blank=True, help_text='Full episode script'),
        ),
        migrations.AddField(
            model_name='episode',
            name='script_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='episode',
            name='script_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('final', 'Final')], default='draft', max_length=50),
        ),
    ]
