# Generated by Django 5.2 on 2026-03-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional storyboard image', null=True, upload_to='storyboards/'),
        ),
    ]
